FROM ruby:3.4.7

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV APP_ROOT=/app

WORKDIR $APP_ROOT

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      default-mysql-client \
      default-libmysqlclient-dev \
      git \
      curl \
      vim \
      imagemagick \
      fonts-noto-cjk \
      pkg-config && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile* ./

RUN bundle install

COPY . .

EXPOSE 3000
